# Generated by Django 4.2.6 on 2024-03-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma_page', '0009_alter_offers_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('cost', models.FloatField(max_length=10)),
                ('days', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
