# Generated by Django 4.2.6 on 2024-03-05 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diploma_page', '0011_planners_dest_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planners',
            old_name='dest_image',
            new_name='planner_image',
        ),
    ]
