# Generated by Django 4.2.6 on 2024-03-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma_page', '0012_rename_dest_image_planners_planner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('cost', models.FloatField(max_length=10)),
                ('days', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('description', models.TextField(max_length=400)),
                ('planner_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('is_special', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Offers',
        ),
        migrations.DeleteModel(
            name='Planners',
        ),
    ]
