# Generated by Django 4.2.6 on 2024-03-10 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diploma_page', '0013_trips_delete_offers_delete_planners'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trips',
            old_name='planner_image',
            new_name='trip_image',
        ),
    ]
