# Generated by Django 4.2.6 on 2024-03-12 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diploma_page', '0015_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='total_price',
        ),
    ]
