# Generated by Django 4.2.6 on 2024-04-22 08:10

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma_page', '0016_remove_orders_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='check_in',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date.today)]),
        ),
        migrations.AlterField(
            model_name='orders',
            name='check_out',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date.today)]),
        ),
    ]
