# Generated by Django 4.2.6 on 2024-04-24 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diploma_page', '0019_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='rating',
        ),
    ]
